### ISSUE TITLE
socket permission error

### ISSUE THREAD

**Issue by namjul** [ZingerLittleBee/netop#32]
While looking for a tool to network request viewer tool, i found this which lookes like what i need (cli and simple). I installed it without using `sudo`. When running i get the follwing error: It spits it out overlayed with a first paint of the UI which is why the horizontal lines are in there:
```
│hread '<unnamed>' panicked at '││lled `Result::unwrap()` on an `││r` valu│: PcapError("socket: Operation not permitted")', /home/n││/.local/share/rtx/installs/rust││.67.1/registry/src/github.com-1││0.0MB/s│ec823/netraffic-0.1.0/src/lib.rs:133:18                 │
```

**Comment by ZingerLittleBee** [comment]
The error `PcapError("socket: Operation not permitted")` indicates that `netop` does not have permission to open a socket. Try running `netop` with sudo or root privileges.
If the issue persists, please let me know what operating system you are using.

**Comment by namjul** [comment]
I currently don't have PATH setup within sudo, so tried running `sudo ./target/release/netop` and it worked. Thanks!
