### ISSUE TITLE
migrate to ratatui

### ISSUE THREAD

**Issue by auronandace** [ZingerLittleBee/netop#42]
I noticed you are using the `tui` library. That is no longer maintained. The successor is `ratatui` which can be found here: https://github.com/ratatui-org/ratatui

Thanks for your neat project!

**Comment by ZingerLittleBee** [comment]
Thanks for pointing that out!
I will certainly look into migrating to ﻿ratatui in the near future.
Appreciate your feedback.

**Comment by ZingerLittleBee** [comment]
finished with fe2f730d1fcedce3502f7c53e334ca4352f4682a
