### ISSUE TITLE
NetBSD package ready

### ISSUE THREAD

**Issue by 0323pin** [ZingerLittleBee/netop#7]
Hi,

I've just packaged and built `netop` on my NetBSD machine.

![2022-06-18-112422_1366x768_scrot](https://user-images.githubusercontent.com/90570748/174431655-09983daa-999a-49d8-b36f-24b04b7b7d05.png)

I'll import the package to the main pkgsrc branch soon.
Would you mind removing `Cargo.lock` from gitignore, so the file is hosted in the repository?
The reason for this is that we have a script that reads `Cargo.lock` and generates a list of dependency crates. Without `Cargo.lock` I need to do this manually.
Thanks!

**Comment by ZingerLittleBee** [comment]
of course
welcome PR

**Comment by 0323pin** [comment]
Thanks, https://github.com/ZingerLittleBee/netop/pull/8

**Comment by 0323pin** [comment]
@ZingerLittleBee Merged, http://mail-index.netbsd.org/pkgsrc-changes/2022/06/18/msg256076.html
